sudo: required
services:
  - docker

before_install:
  - docker build -t fadsey/react -f Dockerfile.dev .

script:
  - docker run -e CI=true fadsey/react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "reactapp"
  env: "Reactapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-770070740319"
  bucket_path: "reactapp"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
